// app/services/data.js
// Pure data - no JSX here to avoid server-side JSX parsing issues
export const servicesData = [
  {
    slug: 'brand-strategy',
    name: 'Brand Strategy',
    shortDesc: 'Strategic brand positioning and narrative development',
    heroHeadline: 'Build a Brand That',
    heroAccent: 'Stands Apart',
    description: "A powerful brand is more than a logo — it's a story, a feeling, a promise. We craft comprehensive brand strategies that define who you are, who you serve, and why you matter in a crowded market.",
    iconPath: 'M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z',
    iconViewBox: '0 0 24 24',
    iconType: 'polygon',
    color: '#FF6B00',
    lightColor: 'rgba(255,107,0,0.1)',
    features: [
      { title: 'Brand Identity Design', desc: 'Logo, color palette, typography, and complete visual language system.' },
      { title: 'Market Positioning', desc: 'Define your unique space in the market and why customers should choose you.' },
      { title: 'Brand Voice & Tone', desc: 'Create a consistent personality across all touchpoints and communication.' },
      { title: 'Competitive Analysis', desc: 'Deep research on your competitive landscape and whitespace opportunities.' },
      { title: 'Brand Guidelines', desc: 'A comprehensive document ensuring brand consistency at scale.' },
      { title: 'Audience Research', desc: 'Data-driven insights into your ideal customers and their behavior.' },
    ],
    process: [
      { step: '01', title: 'Discovery', desc: 'Deep-dive into your business, goals, audience, and competitive landscape.' },
      { step: '02', title: 'Strategy', desc: 'Develop your positioning, messaging architecture, and brand pillars.' },
      { step: '03', title: 'Identity', desc: 'Create your visual identity, voice, and comprehensive brand guidelines.' },
      { step: '04', title: 'Launch', desc: 'Roll out your new brand across all channels with a full activation plan.' },
    ],
    stats: [{ value: '15+', label: 'Brands Built' }, { value: '100%', label: 'Identity Retention' }, { value: '3x', label: 'Avg. Recognition Growth' }],
  },
  {
    slug: 'influencer-marketing',
    name: 'Influencer Marketing',
    shortDesc: 'Creator partnerships and campaign management',
    heroHeadline: 'Reach Millions',
    heroAccent: 'Through Creators',
    description: "Connect with the right creators to amplify your brand message authentically. We manage end-to-end influencer campaigns — from talent sourcing to performance analysis.",
    iconPath: 'M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2|M23 21v-2a4 4 0 0 0-3-3.87|M16 3.13a4 4 0 0 1 0 7.75',
    iconViewBox: '0 0 24 24',
    iconType: 'people',
    color: '#6366f1',
    lightColor: 'rgba(99,102,241,0.1)',
    features: [
      { title: 'Creator Vetting', desc: 'Thorough analysis of creator audiences, engagement rates, and brand fit.' },
      { title: 'Campaign Strategy', desc: 'Custom campaign briefs aligned to your KPIs and brand guidelines.' },
      { title: 'Contract & Negotiations', desc: 'We handle all agreements, usage rights, and compliance.' },
      { title: 'Content Coordination', desc: 'Seamless coordination from briefing to content approval and posting.' },
      { title: 'Performance Tracking', desc: 'Real-time dashboard tracking impressions, reach, and conversions.' },
      { title: 'Post-Campaign Report', desc: 'Detailed analysis with learnings and recommendations for future campaigns.' },
    ],
    process: [
      { step: '01', title: 'Briefing', desc: 'Define campaign goals, target audience, budget, and KPIs.' },
      { step: '02', title: 'Sourcing', desc: 'Identify and vet creators from our network of 500+ verified influencers.' },
      { step: '03', title: 'Execution', desc: 'Coordinate content creation, review, approval, and publishing.' },
      { step: '04', title: 'Analysis', desc: 'Track performance and deliver detailed campaign report.' },
    ],
    stats: [{ value: '500+', label: 'Creator Network' }, { value: '25+', label: 'Campaigns Run' }, { value: '5M+', label: 'Total Reach' }],
  },
  {
    slug: 'content-production',
    name: 'Content Production',
    shortDesc: 'Video, photo, and creative content creation',
    heroHeadline: 'Content That',
    heroAccent: 'Converts & Captivates',
    description: "From concept to final cut, we produce high-quality content that tells your brand story compellingly. Videos, photography, reels, and more — crafted to perform across every platform.",
    iconPath: 'polygon:23 7 16 12 23 17 23 7|rect:1 5 15 14',
    iconViewBox: '0 0 24 24',
    iconType: 'video',
    color: '#10b981',
    lightColor: 'rgba(16,185,129,0.1)',
    features: [
      { title: 'Brand Films', desc: 'Cinematic brand storytelling that makes a lasting emotional impact.' },
      { title: 'Short-Form Video', desc: 'Reels, TikToks, and YouTube Shorts optimised for maximum reach.' },
      { title: 'Product Photography', desc: 'Studio and lifestyle photography that makes your products irresistible.' },
      { title: 'Scripting & Storyboarding', desc: 'Creative scripting and visual storyboards before a single shot is taken.' },
      { title: 'Motion Graphics', desc: 'Animated graphics and visual effects that elevate your content quality.' },
      { title: 'Post-Production', desc: 'Professional editing, color grading, sound design, and delivery.' },
    ],
    process: [
      { step: '01', title: 'Concept', desc: 'Creative brief, moodboard, and concept development aligned to your brand.' },
      { step: '02', title: 'Pre-Production', desc: 'Script, storyboard, location scouting, casting, and production planning.' },
      { step: '03', title: 'Production', desc: 'Professional filming/photography with expert crew and equipment.' },
      { step: '04', title: 'Post & Delivery', desc: 'Editing, color, sound, and platform-optimised delivery formats.' },
    ],
    stats: [{ value: '100+', label: 'Videos Produced' }, { value: '4K', label: 'Production Quality' }, { value: '48hr', label: 'Turnaround' }],
  },
  {
    slug: 'social-media',
    name: 'Social Media Management',
    shortDesc: 'Full social media management and growth',
    heroHeadline: 'Grow Your',
    heroAccent: 'Social Presence',
    description: "We manage your entire social media presence — from strategy and content creation to community management and growth hacking. So you can focus on running your business.",
    iconType: 'share',
    color: '#f59e0b',
    lightColor: 'rgba(245,158,11,0.1)',
    features: [
      { title: 'Content Calendar', desc: 'Strategic monthly content calendar aligned to campaigns and key dates.' },
      { title: 'Content Creation', desc: 'Platform-native content designed and written by our creative team.' },
      { title: 'Community Management', desc: 'Active comment and DM management to build a loyal community.' },
      { title: 'Hashtag Strategy', desc: 'Data-driven hashtag research to maximise organic reach.' },
      { title: 'Platform Optimisation', desc: 'Profile optimisation and bio strategy for each platform.' },
      { title: 'Monthly Analytics', desc: 'Detailed monthly reports with growth metrics and recommendations.' },
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Comprehensive review of your current social presence and benchmarks.' },
      { step: '02', title: 'Strategy', desc: 'Platform-specific strategy, content pillars, and posting schedule.' },
      { step: '03', title: 'Create & Post', desc: 'Daily content creation, scheduling, and platform management.' },
      { step: '04', title: 'Optimise', desc: 'Monthly performance review and strategy refinement based on data.' },
    ],
    stats: [{ value: '20+', label: 'Brands Managed' }, { value: '10x', label: 'Avg. Growth' }, { value: '365', label: 'Days Coverage' }],
  },
  {
    slug: 'paid-media',
    name: 'Paid Media & Ads',
    shortDesc: 'Strategic ad campaigns across all platforms',
    heroHeadline: 'Ads That',
    heroAccent: 'Drive Real Results',
    description: "Smart paid media campaigns designed to reach the right people at the right time. We manage your ad spend across Meta, Google, YouTube, and more to maximise your return.",
    iconType: 'chart',
    color: '#ef4444',
    lightColor: 'rgba(239,68,68,0.1)',
    features: [
      { title: 'Campaign Strategy', desc: 'Full-funnel ad strategy from awareness to conversion.' },
      { title: 'Ad Creative Design', desc: 'High-performing ad creatives optimised for each platform format.' },
      { title: 'Audience Research', desc: 'Precise audience targeting using first and third-party data.' },
      { title: 'Meta Ads Management', desc: 'Facebook and Instagram ad campaigns with expert optimisation.' },
      { title: 'Google Ads', desc: 'Search, display, and shopping campaigns for high-intent traffic.' },
      { title: 'A/B Testing', desc: 'Systematic creative and audience testing to improve performance over time.' },
    ],
    process: [
      { step: '01', title: 'Research', desc: 'Audience research, competitor analysis, and platform selection.' },
      { step: '02', title: 'Launch', desc: 'Creative production, campaign setup, tracking, and go-live.' },
      { step: '03', title: 'Optimise', desc: 'Daily monitoring, bid management, and A/B test iterations.' },
      { step: '04', title: 'Report', desc: 'Weekly and monthly performance reports with data-backed recommendations.' },
    ],
    stats: [{ value: '3x', label: 'Avg. ROAS' }, { value: '₹50L+', label: 'Ad Spend Managed' }, { value: '40%', label: 'Lower CPA' }],
  },
  {
    slug: 'video-production',
    name: 'Video Production',
    shortDesc: 'Professional video production for brands',
    heroHeadline: 'Stories Worth',
    heroAccent: 'Watching',
    description: "Cinematic video production that captures attention and inspires action. From corporate films to brand campaigns and documentary-style content — we make it real.",
    iconType: 'play',
    color: '#8b5cf6',
    lightColor: 'rgba(139,92,246,0.1)',
    features: [
      { title: 'Brand Films', desc: 'Long-form cinematic stories that define your brand identity.' },
      { title: 'Corporate Videos', desc: 'Professional corporate communication and internal training videos.' },
      { title: 'Product Videos', desc: 'Polished product demo and explainer videos that drive purchase decisions.' },
      { title: 'Event Coverage', desc: 'Multi-camera event documentation and highlight reels.' },
      { title: 'Testimonial Videos', desc: 'Authentic customer stories that build trust and social proof.' },
      { title: 'Documentary Style', desc: 'In-depth storytelling that puts your brand mission at center stage.' },
    ],
    process: [
      { step: '01', title: 'Pre-Production', desc: 'Creative concept, scripting, casting, location scouting, and scheduling.' },
      { step: '02', title: 'Production', desc: 'Professional shoot with expert director, DP, crew, and equipment.' },
      { step: '03', title: 'Post-Production', desc: 'Editing, color grade, sound design, VFX, and motion graphics.' },
      { step: '04', title: 'Delivery', desc: 'Platform-optimised exports in all required formats and resolutions.' },
    ],
    stats: [{ value: '50+', label: 'Videos Produced' }, { value: '4K', label: 'Resolution Quality' }, { value: '2x', label: 'More Engagement' }],
  },
  {
    slug: 'web-development',
    name: 'Web Design & Development',
    shortDesc: 'Custom website design and development',
    heroHeadline: 'Websites That',
    heroAccent: 'Convert & Impress',
    description: "Beautiful, fast, and conversion-focused websites built to represent your brand and drive business results. From landing pages to full e-commerce stores.",
    iconType: 'browser',
    color: '#0ea5e9',
    lightColor: 'rgba(14,165,233,0.1)',
    features: [
      { title: 'UI/UX Design', desc: 'User-centric design that looks stunning and converts visitors into customers.' },
      { title: 'Landing Pages', desc: 'High-converting landing pages built for campaigns and product launches.' },
      { title: 'E-Commerce', desc: 'Shopify and custom e-commerce stores designed to maximise sales.' },
      { title: 'Corporate Websites', desc: 'Professional multi-page websites for businesses and agencies.' },
      { title: 'SEO Optimisation', desc: 'On-page SEO, performance optimisation, and schema markup built-in.' },
      { title: 'Maintenance', desc: 'Ongoing support, updates, and performance monitoring post-launch.' },
    ],
    process: [
      { step: '01', title: 'Discovery', desc: 'Requirements gathering, competitor analysis, and sitemap planning.' },
      { step: '02', title: 'Design', desc: 'Wireframes, moodboards, and high-fidelity UI mockups for review.' },
      { step: '03', title: 'Build', desc: 'Development with clean code, pixel-perfect implementation, and testing.' },
      { step: '04', title: 'Launch', desc: 'QA testing, SEO setup, deployment, and post-launch monitoring.' },
    ],
    stats: [{ value: '30+', label: 'Sites Launched' }, { value: '99%', label: 'Uptime' }, { value: '2s', label: 'Load Time' }],
  },
  {
    slug: 'consulting',
    name: 'Strategic Consulting',
    shortDesc: 'Expert marketing advisory and sessions',
    heroHeadline: 'Strategy From',
    heroAccent: 'Experts Who Do',
    description: "Get direct access to our senior strategists for focused consulting sessions. Whether you need a marketing audit, go-to-market strategy, or ongoing advisory — we bring clarity.",
    iconType: 'lightbulb',
    color: '#ec4899',
    lightColor: 'rgba(236,72,153,0.1)',
    features: [
      { title: 'Marketing Audit', desc: 'Comprehensive review of your current marketing and growth gaps.' },
      { title: 'Go-To-Market Strategy', desc: 'Launch strategy for new products, markets, or brand repositioning.' },
      { title: 'Growth Roadmap', desc: 'A prioritised 3-6 month marketing execution plan with clear milestones.' },
      { title: 'Team Training', desc: 'Workshops and training for your in-house marketing team.' },
      { title: 'Fractional CMO', desc: 'Ongoing strategic guidance at a fraction of a full-time hire.' },
      { title: 'Crisis Management', desc: 'Brand reputation management and crisis communication strategy.' },
    ],
    process: [
      { step: '01', title: 'Intake', desc: 'Initial discovery call and brief to understand your situation and goals.' },
      { step: '02', title: 'Audit', desc: 'Deep analysis of your business, market, and current marketing efforts.' },
      { step: '03', title: 'Strategy', desc: 'Deliver a tailored strategy document with actionable recommendations.' },
      { step: '04', title: 'Support', desc: 'Ongoing advisory, check-ins, and accountability sessions.' },
    ],
    stats: [{ value: '40+', label: 'Consulting Sessions' }, { value: '95%', label: 'Client Satisfaction' }, { value: '2x', label: 'Faster Growth' }],
  },
];

export const servicesBySlug = Object.fromEntries(servicesData.map(s => [s.slug, s]));
